name: KeepAlive Ping

on:
  schedule:
    - cron: "*/5 * * * *"   # 5분마다(UTC)
  workflow_dispatch:

concurrency:
  group: keepalive-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions: {}

    steps:
      # 초 단위 지터로 충돌 완화
      - name: Random jitter
        run: sleep $((RANDOM % 20))

      - name: Show tick (UTC)
        run: date -u +"UTC %Y-%m-%d %H:%M:%S"

      - name: Ping /health
        env:
          HEALTH_URL: https://fastapi-trading-bot-9rme.onrender.com/health
        run: |
          set -e
          for i in 1 2 3; do
            code=$(curl -sS -o /dev/null -w "%{http_code}" --max-time 10 "$HEALTH_URL" || true)
            echo "attempt $i -> HTTP $code"
            [ "$code" = "200" ] && exit 0
            sleep 6
          done
          echo "Ping failed."; exit 1
