name: KeepAlive Ping

on:
  schedule:
    - cron: "*/5 * * * *"      # 5분마다 (UTC 기준)
  workflow_dispatch:           # 수동 실행 버튼

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions: {}            # 최소 권한
    concurrency:
      group: keepalive-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Jitter (spread load)
        run: sleep $((RANDOM % 60))   # 정각 몰림 방지(0~59초 랜덤 대기)

      - name: Ping /health
        env:
          HEALTH_URL: ${{ secrets.HEALTH_URL }}
        run: |
          set -e
          for i in 1 2 3; do
            code=$(curl -sS -o /dev/null -w "%{http_code}" --max-time 10 "$HEALTH_URL" || true)
            echo "attempt $i => HTTP $code"
            [ "$code" = "200" ] && exit 0
            sleep 5
          done
          echo "Ping failed (3 attempts)."
          exit 1
