name: KeepAlive Ping

on:
  schedule:
    - cron: "1-59/3 * * * *"    # 01,04,07,...,58 (UTC) → 정각(:00) 절대 미포함
  workflow_dispatch:

concurrency:
  group: keepalive-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions: {}

    steps:
      - name: Random jitter (spread load)
        run: sleep $((RANDOM % 45))   # 0~44초 랜덤 대기

      - name: Show schedule tick (debug)
        run: date -u +"UTC %Y-%m-%d %H:%M:%S"

      - name: Ping /health
        env:
          HEALTH_URL: ${{ secrets.HEALTH_URL }}   # 예: https://<your-app>.onrender.com/health
        run: |
          set -e
          for i in 1 2 3; do
            code=$(curl -sS -o /dev/null -w "%{http_code}" --max-time 10 "$HEALTH_URL" || true)
            echo "attempt $i -> HTTP $code"
            [ "$code" = "200" ] && exit 0
            sleep 6
          done
          echo "Ping failed."
          exit 1
