name: KeepAlive Ping

on:
  schedule:
    # 정각(:00)을 피해서 5분 간격 유지 (UTC 기준)
    # 03,08,13,18,23,28,33,38,43,48,53,58 분에만 실행
    - cron: "3,8,13,18,23,28,33,38,43,48,53,58 * * * *"
  workflow_dispatch:           # 수동 실행 버튼

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions: {}            # 최소 권한
    concurrency:
      group: keepalive-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Jitter (spread load)
        run: sleep $((RANDOM % 60))   # 시작 시각 분산(충돌 완화)

      - name: Ping /health
        env:
          HEALTH_URL: ${{ secrets.HEALTH_URL }}
        run: |
          set -e
          for i in 1 2 3; do
            code=$(curl -sS -o /dev/null -w "%{http_code}" --max-time 10 "$HEALTH_URL" || true)
            echo "attempt $i => HTTP $code"
            [ "$code" = "200" ] && exit 0
            sleep 5
          done
          echo "Ping failed (3 attempts)."
          exit 1
